sonar.host.url=http://localhost:9000

# Kunci project (Sesuai nama di dashboard kamu)
sonar.projectKey=Portofolio-Mardhea
sonar.projectName=Portofolio Mardhea
sonar.projectVersion=1.0

# Sumber kode
sonar.sources=.
sonar.inclusions=**/*.js,**/*.html,**/*.css
sonar.exclusions=node_modules/**,uploads/**,.git/**,*.log,coverage/**
sonar.sourceEncoding=UTF-8